"""将 TestHub 压测场景（PerfScenario 快照）转换为 JMeter .jmx 测试计划。

设计要点：
- 纯函数、无 Django 依赖，便于单元测试（见 tests/test_jmx_builder.py）。
- 生成结构遵循 JMeter 5.x 的 hashTree 嵌套约定，保证 `jmeter -n -t plan.jmx` 可直接运行。
- 仅覆盖压测常用子集：ThreadGroup（并发/爬坡/时长）、HTTP 请求（域/路径/方法/头/体）、
  响应断言（状态码/包含/不包含）、固定思考时间。复杂协议（JDBC/JMS 等）
  建议用户直接上传 .jmx（模式二），本生成器不强行覆盖。
"""
import json
import xml.etree.ElementTree as ET
from urllib.parse import urlparse

XML_DECLARATION = '<?xml version="1.0" encoding="UTF-8"?>\n'


def _parse_form_body(body):
    """FORM body 文本 → dict（兼容 JSON 对象与 k=v&k=v 两种历史格式）。"""
    if not (body or '').strip():
        return {}
    try:
        parsed = json.loads(body)
        if isinstance(parsed, dict):
            return parsed
    except (ValueError, TypeError):
        pass
    return dict(p.split('=', 1) for p in body.split('&') if '=' in p)


def _prop(tag, name, text):
    el = ET.Element(tag, {'name': name})
    if text is not None:
        el.text = str(text)
    return el


def _hashtree(*children):
    ht = ET.Element('hashTree')
    for child in children:
        ht.append(child)
    return ht


def _testplan(variables):
    tp = ET.Element('TestPlan', {'guiclass': 'TestPlanGui', 'testclass': 'TestPlan',
                                 'testname': 'TestHub Perf Plan', 'enabled': 'true'})
    tp.append(_prop('stringProp', 'TestPlan.comments', 'Generated by TestHub'))
    tp.append(_prop('boolProp', 'TestPlan.functional_mode', 'false'))
    tp.append(_prop('boolProp', 'TestPlan.tearDown_on_shutdown', 'true'))
    tp.append(_prop('boolProp', 'TestPlan.serialize_threadgroups', 'false'))
    args = _prop('elementProp', 'TestPlan.user_defined_variables', None)
    args.set('elementType', 'Arguments')
    args.set('guiclass', 'ArgumentsPanel')
    args.set('testclass', 'Arguments')
    args.set('testname', 'User Defined Variables')
    coll = _prop('collectionProp', 'Arguments.arguments', None)
    for var in (variables or []):
        name = var.get('name')
        if not name:
            continue
        item = _prop('elementProp', '', None)
        item.set('elementType', 'Argument')
        item.append(_prop('stringProp', 'Argument.name', name))
        item.append(_prop('stringProp', 'Argument.value', str(var.get('value', ''))))
        item.append(_prop('stringProp', 'Argument.metadata', '='))
        coll.append(item)
    args.append(coll)
    tp.append(args)
    return tp


def _threadgroup(load_config):
    concurrency = max(int(load_config.get('concurrency') or 1), 1)
    ramp_up = max(int(load_config.get('ramp_up') or 0), 0)
    duration = max(int(load_config.get('duration') or 0), 0)

    tg = ET.Element('ThreadGroup', {'guiclass': 'ThreadGroupGui', 'testclass': 'ThreadGroup',
                                    'testname': 'ThreadGroup', 'enabled': 'true'})
    tg.append(_prop('stringProp', 'ThreadGroup.on_sample_error', 'continue'))
    ctrl = _prop('elementProp', 'ThreadGroup.main_controller', None)
    ctrl.set('elementType', 'LoopController')
    ctrl.set('guiclass', 'LoopControlPanel')
    ctrl.set('testclass', 'LoopController')
    ctrl.set('testname', 'Loop Controller')
    ctrl.append(_prop('boolProp', 'LoopController.continue_forever', 'false'))
    ctrl.append(_prop('intProp', 'LoopController.loops', '-1'))
    tg.append(ctrl)
    tg.append(_prop('intProp', 'ThreadGroup.num_threads', concurrency))
    tg.append(_prop('intProp', 'ThreadGroup.ramp_time', ramp_up))
    tg.append(_prop('boolProp', 'ThreadGroup.scheduler', 'true'))
    tg.append(_prop('longProp', 'ThreadGroup.duration', duration))
    tg.append(_prop('longProp', 'ThreadGroup.delay', 0))
    return tg


def _split_url(url):
    parsed = urlparse(url or '')
    scheme = parsed.scheme or 'http'
    domain = parsed.netloc or ''
    path = parsed.path or '/'
    if parsed.query:
        path = f'{path}?{parsed.query}'
    # 相对 URL（无 netloc）时整体作为 path 兜底
    if not domain and parsed.netloc == '' and (parsed.path or parsed.query):
        path = url
    return scheme, domain, path


def _form_argument(name, value):
    """构造一个命名的 HTTPArgument（multipart 表单文本字段）。"""
    item = _prop('elementProp', '', None)
    item.set('elementType', 'HTTPArgument')
    item.append(_prop('boolProp', 'HTTPArgument.always_encode', 'true'))
    item.append(_prop('stringProp', 'Argument.value', str(value)))
    item.append(_prop('stringProp', 'Argument.name', str(name)))
    item.append(_prop('stringProp', 'Argument.metadata', '='))
    return item


def _http_sampler(step):
    name = step.get('name') or 'step'
    method = (step.get('method') or 'GET').upper()
    scheme, domain, path = _split_url(step.get('url') or '')

    sampler = ET.Element('HTTPSamplerProxy', {'guiclass': 'HttpTestSampleGui',
                                              'testclass': 'HTTPSamplerProxy', 'testname': name,
                                              'enabled': 'true'})
    args = _prop('elementProp', 'HTTPsampler.Arguments', None)
    args.set('elementType', 'Arguments')
    args.set('guiclass', 'HTTPArgumentsPanel')
    args.set('testclass', 'Arguments')
    coll = _prop('collectionProp', 'Arguments.arguments', None)
    body = step.get('body') or ''
    step_files = [f for f in (step.get('files') or []) if (f or {}).get('path')]
    is_multipart = ((step.get('body_type') or '').upper() == 'FORM' and step_files)
    if is_multipart:
        # multipart/form-data：body 文本按命名表单字段发送，文件走 HTTPFileUpload
        for k, v in _parse_form_body(body).items():
            coll.append(_form_argument(k, v))
    elif body:
        item = _prop('elementProp', '', None)
        item.set('elementType', 'HTTPArgument')
        item.append(_prop('boolProp', 'HTTPArgument.always_encode', 'false'))
        item.append(_prop('stringProp', 'Argument.value', body))
        item.append(_prop('stringProp', 'Argument.name', ''))
        item.append(_prop('stringProp', 'Argument.metadata', '='))
        coll.append(item)
    args.append(coll)
    sampler.append(args)

    if is_multipart:
        # 文件上传：HTTPsampler.files 集合 + DO_MULTIPART_POST 开关，
        # 二者缺一 JMeter 都会退化成普通表单提交
        files = _prop('elementProp', 'HTTPsampler.Files', None)
        files.set('elementType', 'HTTPFileArgs')
        fcoll = _prop('collectionProp', 'HTTPFileArgs.files', None)
        for f in step_files:
            fitem = _prop('elementProp', f.get('path'), None)
            fitem.set('elementType', 'HTTPFileArg')
            fitem.append(_prop('stringProp', 'File.path', f.get('path')))
            fitem.append(_prop('stringProp', 'File.paramname', f.get('field') or 'file'))
            fitem.append(_prop('stringProp', 'File.mimetype',
                               f.get('content_type') or 'application/octet-stream'))
            fcoll.append(fitem)
        files.append(fcoll)
        sampler.append(files)
        sampler.append(_prop('boolProp', 'HTTPSampler.DO_MULTIPART_POST', 'true'))

    sampler.append(_prop('stringProp', 'HTTPSampler.domain', domain))
    sampler.append(_prop('stringProp', 'HTTPSampler.port', ''))
    sampler.append(_prop('stringProp', 'HTTPSampler.protocol', scheme))
    sampler.append(_prop('stringProp', 'HTTPSampler.path', path))
    sampler.append(_prop('stringProp', 'HTTPSampler.method', method))
    sampler.append(_prop('stringProp', 'HTTPSampler.contentEncoding', 'UTF-8'))
    sampler.append(_prop('stringProp', 'HTTPSampler.implementation', 'HttpClient4'))
    sampler.append(_prop('boolProp', 'HTTPSampler.follow_redirects', 'true'))
    sampler.append(_prop('boolProp', 'HTTPSampler.auto_redirects', 'false'))
    sampler.append(_prop('boolProp', 'HTTPSampler.use_keepalive', 'true'))

    children = _hashtree()
    headers = step.get('headers') or {}
    if headers:
        hm = ET.Element('HeaderManager', {'guiclass': 'HeaderPanel', 'testclass': 'HeaderManager',
                                          'testname': 'HTTP Header Manager', 'enabled': 'true'})
        hcoll = _prop('collectionProp', 'HeaderManager.headers', None)
        for k, v in headers.items():
            if not k:
                continue
            item = _prop('elementProp', '', None)
            item.set('elementType', 'Header')
            item.append(_prop('stringProp', 'Header.name', str(k)))
            item.append(_prop('stringProp', 'Header.value', str(v)))
            hcoll.append(item)
        hm.append(hcoll)
        children.append(hm)

    assertions = step.get('assertions') or []
    if assertions:
        children.append(_response_assertion(assertions))

    think = step.get('think_time') or {}
    ttype = (think.get('type') or 'NONE').upper()
    if ttype in ('FIXED', 'RANDOM') and float(think.get('min') or 0) > 0:
        delay_ms = int(float(think.get('min')) * 1000)
        timer = ET.Element('ConstantTimer', {'guiclass': 'ConstantTimerGui', 'testclass': 'ConstantTimer',
                                            'testname': 'Think Time', 'enabled': 'true'})
        timer.append(_prop('stringProp', 'ConstantTimer.delay', delay_ms))
        children.append(timer)

    return sampler, children


def _response_assertion(assertions):
    ra = ET.Element('ResponseAssertion', {'guiclass': 'AssertionGui', 'testclass': 'ResponseAssertion',
                                         'testname': 'Response Assertion', 'enabled': 'true'})
    strings = _prop('collectionProp', 'Asserion.test_strings', None)
    # 每个断言项：选择字段 + 匹配类型
    # 默认响应体 + 包含；状态码用 response_code + Equals
    field = 'Assertion.response_data'
    test_types = []
    for a in assertions:
        atype = (a.get('type') or '').upper()
        expected = a.get('expected') or ''
        strings.append(_prop('stringProp', '', expected))
        if atype == 'STATUS_CODE':
            field = 'Assertion.response_code'
            test_types.append(8)      # Equals
        elif atype == 'NOT_CONTAINS':
            test_types.append(16)     # Not Contains（位掩码）
        else:                         # CONTAINS / 默认
            test_types.append(2)      # Contains
    ra.append(strings)
    ra.append(_prop('stringProp', 'Assertion.test_field', field))
    ra.append(_prop('stringProp', 'Assertion.custom_message', ''))
    # test_type 取各断言类型的按位或
    ra.append(_prop('intProp', 'Assertion.test_type', str(sum(set(test_types)) or 2)))
    return ra


def build_jmx(snapshot, runtime=None):
    """由场景快照生成 .jmx 字符串。

    :param snapshot: dict，含 load_config / steps / variables（与执行快照结构一致）
    :param runtime: dict（可选），预留（如 CSV 文件映射）
    :return: JMeter .jmx 文本
    """
    load_config = snapshot.get('load_config') or {}
    variables = snapshot.get('variables') or []
    steps = [s for s in (snapshot.get('steps') or []) if s.get('enabled', True)]

    root = ET.Element('jmeterTestPlan',
                      {'version': '1.2', 'properties': '5.0', 'jmeter': '5.6.3'})

    thread_hash = _hashtree()
    thread_hash.append(_threadgroup(load_config))
    step_tree = _hashtree()
    for step in steps:
        sampler, children = _http_sampler(step)
        step_tree.append(sampler)
        step_tree.append(children)
    thread_hash.append(step_tree)

    plan_hash = _hashtree()
    plan_hash.append(_testplan(variables))
    plan_hash.append(thread_hash)

    root.append(plan_hash)

    body = ET.tostring(root, encoding='unicode')
    return XML_DECLARATION + body
