# Generated by Django 4.2.7 on 2026-08-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfexecution',
            name='scheduled_task',
            field=models.ForeignKey(blank=True, db_comment='来源定时任务(手动执行为空)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='perf_testing.perfscheduledtask', verbose_name='来源定时任务'),
        ),
    ]
