# Generated by Django 4.2.7 on 2026-08-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0002_perfexecution_scheduled_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfexecution',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, db_comment='分享直链过期时间(空=永不过期)', null=True, verbose_name='分享过期时间'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='share_token',
            field=models.CharField(blank=True, db_comment='报告分享直链令牌(空=未分享)', max_length=64, null=True, unique=True, verbose_name='分享令牌'),
        ),
    ]
