# Generated by Django 4.2.7 on 2026-08-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0003_perfexecution_share_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfexecution',
            name='script_ref',
            field=models.JSONField(blank=True, db_comment='执行模式与脚本引用；模式 script 时含 jmx_path（直接上传的 .jmx）', default=dict, verbose_name='脚本引用'),
        ),
        migrations.AlterField(
            model_name='perfscenario',
            name='engine',
            field=models.CharField(choices=[('BUILTIN', '内置引擎(asyncio+httpx)'), ('LOCUST', 'Locust'), ('JMETER', 'JMeter')], db_comment='压测引擎', default='BUILTIN', max_length=20, verbose_name='压测引擎'),
        ),
    ]
