# Generated by Django 4.2.7 on 2026-08-04 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perf_testing', '0005_perfdatafile_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='环境名称', max_length=200, verbose_name='环境名称')),
                ('scope', models.CharField(choices=[('GLOBAL', '全局环境'), ('PROJECT', '项目环境')], db_comment='作用域(GLOBAL/PROJECT)', default='PROJECT', max_length=10, verbose_name='作用域')),
                ('base_url', models.CharField(blank=True, db_comment='环境基础地址(如 https://api.example.com)', default='', max_length=500, verbose_name='基础地址')),
                ('headers', models.JSONField(blank=True, db_comment='环境级全局请求头(JSON:{k:v})', default=dict, verbose_name='全局请求头')),
                ('verify_ssl', models.BooleanField(db_comment='是否校验 SSL 证书', default=False, verbose_name='校验 SSL 证书')),
                ('variables', models.JSONField(blank=True, db_comment='环境变量列表(JSON:[{name,type,value}])', default=list, verbose_name='环境变量')),
                ('is_active', models.BooleanField(db_comment='是否激活(同作用域内唯一)', default=False, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
                ('created_by', models.ForeignKey(db_comment='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, db_comment='关联压测项目(PROJECT 作用域必填)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='perf_testing.perfproject', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '压测环境',
                'verbose_name_plural': '压测环境',
                'db_table': 'perf_environments',
                'db_table_comment': '压测环境',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope', 'is_active'], name='perf_env_scope_active_idx'), models.Index(fields=['project', 'scope'], name='perf_env_proj_scope_idx')],
            },
        ),
    ]
