# Generated by Django 4.2.7 on 2026-08-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0006_perfenvironment'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfscenariostep',
            name='files',
            field=models.JSONField(blank=True, db_comment='multipart文件字段(JSON:[{field,file_id,filename,content_type}])，file_id 指向 PerfDataFile(file_type=UPLOAD)', default=list, verbose_name='文件上传字段'),
        ),
        migrations.AlterField(
            model_name='perfdatafile',
            name='file_type',
            field=models.CharField(choices=[('CSV', 'CSV 参数化数据'), ('JMX', 'JMeter 脚本'), ('UPLOAD', '请求上传文件')], db_comment='文件类型：CSV参数化数据/JMX脚本', default='CSV', max_length=10, verbose_name='文件类型'),
        ),
    ]
