# Generated by Django 4.2.7 on 2026-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0007_perfscenariostep_files_alter_perfdatafile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfscenario',
            name='perf_targets',
            field=models.JSONField(blank=True, db_comment='验收目标(JSON:{max_p95_rt,max_avg_rt,min_tps,max_error_rate})', default=dict, verbose_name='验收目标'),
        ),
    ]
