# Generated by Django 4.2.7 on 2026-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0008_add_perf_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfexecution',
            name='verdict',
            field=models.CharField(choices=[('PASSED', '通过'), ('FAILED', '未通过'), ('NOT_EVALUATED', '未评估')], db_comment='验收目标判定(PASSED/FAILED/NOT_EVALUATED)', default='NOT_EVALUATED', max_length=20, verbose_name='验收判定'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='verdict_details',
            field=models.JSONField(blank=True, db_comment='验收判定明细(JSON:[{step,target,actual,result}])', default=list, verbose_name='验收明细'),
        ),
    ]
