# Generated by Django 4.2.7 on 2026-08-12 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perf_testing', '0009_add_verdict_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='报告标题', max_length=200, verbose_name='报告标题')),
                ('execution_ids', models.JSONField(db_comment='参与对比的执行ID列表(2~5个，保持顺序)', default=list, verbose_name='参与对比的执行ID列表')),
                ('reference_execution_id', models.IntegerField(blank=True, db_comment='基准执行ID', null=True, verbose_name='基准执行ID')),
                ('snapshot', models.JSONField(db_comment='指标矩阵快照(同 compare API 结构)', default=dict, verbose_name='对照快照')),
                ('ai_analysis', models.TextField(blank=True, db_comment='AI对照分析(markdown)', null=True, verbose_name='AI对照分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('created_by', models.ForeignKey(db_comment='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='perf_comparison_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(db_comment='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reports', to='perf_testing.perfproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '压测多轮对照报告',
                'verbose_name_plural': '压测多轮对照报告',
                'db_table': 'perf_comparison_reports',
                'db_table_comment': '压测多轮对照报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
