# Generated by Django 4.2.7 on 2026-09-17 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perf_testing', '0016_project_catalog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfproject',
            name='pool_config',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='perfscenario',
            name='is_preparation',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='PerfPreparedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=1100)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('source_catalog_version', models.PositiveIntegerField()),
                ('source_hash', models.CharField(max_length=64)),
                ('source_asset_hash', models.CharField(max_length=64)),
                ('source_metadata', models.JSONField(default=dict)),
                ('request', models.JSONField(default=dict)),
                ('preparation', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('context_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(default='blocked', max_length=20)),
                ('gaps', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_requests', to='perf_testing.perfproject')),
            ],
            options={
                'db_table': 'perf_prepared_requests',
            },
        ),
        migrations.CreateModel(
            name='PerfPreparationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=64)),
                ('launch_state', models.CharField(default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('entries', models.JSONField(default=list)),
                ('context_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perf_testing.perfexecution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_batches', to='perf_testing.perfproject')),
                ('scenario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perf_testing.perfscenario')),
            ],
            options={
                'db_table': 'perf_preparation_batches',
            },
        ),
        migrations.AddConstraint(
            model_name='perfpreparedrequest',
            constraint=models.UniqueConstraint(fields=('project', 'source_key'), name='perf_prepared_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='perfpreparationbatch',
            constraint=models.UniqueConstraint(fields=('project', 'created_by', 'request_key'), name='perf_preparation_request_unique'),
        ),
    ]
