# Generated by Django 4.2.7 on 2026-09-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_testing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perf_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfscheduledtask',
            name='created_by',
            field=models.ForeignKey(db_comment='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='perf_scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='perfscheduledtask',
            name='scenario',
            field=models.ForeignKey(db_comment='压测场景', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='perf_testing.perfscenario', verbose_name='压测场景'),
        ),
        migrations.AddField(
            model_name='perfscenariostep',
            name='scenario',
            field=models.ForeignKey(db_comment='所属场景', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='perf_testing.perfscenario', verbose_name='所属场景'),
        ),
        migrations.AddField(
            model_name='perfscenariostep',
            name='source_request',
            field=models.ForeignKey(blank=True, db_comment='来源接口用例(用于溯源)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_steps', to='api_testing.apirequest', verbose_name='来源接口用例'),
        ),
        migrations.AddField(
            model_name='perfscenario',
            name='created_by',
            field=models.ForeignKey(db_comment='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='created_perf_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='perfscenario',
            name='project',
            field=models.ForeignKey(db_comment='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='perf_testing.perfproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='perfrequeststat',
            name='execution',
            field=models.ForeignKey(db_comment='所属执行', on_delete=django.db.models.deletion.CASCADE, related_name='request_stats', to='perf_testing.perfexecution', verbose_name='所属执行'),
        ),
        migrations.AddField(
            model_name='perfproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='perf_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='perfproject',
            name='owner',
            field=models.ForeignKey(db_comment='负责人', on_delete=django.db.models.deletion.CASCADE, related_name='owned_perf_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='perfmetricsample',
            name='execution',
            field=models.ForeignKey(db_comment='所属执行', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='perf_testing.perfexecution', verbose_name='所属执行'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, db_comment='执行人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='project',
            field=models.ForeignKey(db_comment='所属项目(冗余，便于项目维度直查)', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='perf_testing.perfproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='scenario',
            field=models.ForeignKey(db_comment='压测场景', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='perf_testing.perfscenario', verbose_name='压测场景'),
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='scheduled_task',
            field=models.ForeignKey(blank=True, db_comment='来源定时任务(手动执行为空)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='perf_testing.perfscheduledtask', verbose_name='来源定时任务'),
        ),
        migrations.AddField(
            model_name='perfenvironment',
            name='created_by',
            field=models.ForeignKey(db_comment='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='perfenvironment',
            name='project',
            field=models.ForeignKey(blank=True, db_comment='关联压测项目(PROJECT 作用域必填)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='perf_testing.perfproject', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='perfdatafile',
            name='project',
            field=models.ForeignKey(db_comment='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='perf_testing.perfproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='perfdatafile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_comment='上传人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_data_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='perfcomparisonreport',
            name='created_by',
            field=models.ForeignKey(db_comment='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='perf_comparison_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='perfcomparisonreport',
            name='project',
            field=models.ForeignKey(db_comment='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reports', to='perf_testing.perfproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='perfbaseline',
            name='execution',
            field=models.ForeignKey(blank=True, db_comment='基线来源执行', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='perf_testing.perfexecution', verbose_name='基线来源执行'),
        ),
        migrations.AddField(
            model_name='perfbaseline',
            name='scenario',
            field=models.OneToOneField(db_comment='压测场景', on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='perf_testing.perfscenario', verbose_name='压测场景'),
        ),
        migrations.AddField(
            model_name='perfbaseline',
            name='set_by',
            field=models.ForeignKey(blank=True, db_comment='设置人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_baselines', to=settings.AUTH_USER_MODEL, verbose_name='设置人'),
        ),
        migrations.AddIndex(
            model_name='perfscheduledtask',
            index=models.Index(fields=['status', 'next_run_at'], name='perf_sched_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='perfscenariostep',
            index=models.Index(fields=['scenario', 'order'], name='perf_step_scen_order_idx'),
        ),
        migrations.AddIndex(
            model_name='perfscenario',
            index=models.Index(fields=['project', '-created_at'], name='perf_scen_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='perfrequeststat',
            index=models.Index(fields=['execution'], name='perf_stat_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='perfmetricsample',
            index=models.Index(fields=['execution', 'ts_offset'], name='perf_sample_exec_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='perfexecution',
            index=models.Index(fields=['-start_time'], name='perf_exec_start_idx'),
        ),
        migrations.AddIndex(
            model_name='perfexecution',
            index=models.Index(fields=['scenario', '-created_at'], name='perf_exec_scen_created_idx'),
        ),
        migrations.AddIndex(
            model_name='perfexecution',
            index=models.Index(fields=['status'], name='perf_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='perfenvironment',
            index=models.Index(fields=['scope', 'is_active'], name='perf_env_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='perfenvironment',
            index=models.Index(fields=['project', 'scope'], name='perf_env_proj_scope_idx'),
        ),
    ]
