# Generated by Django 4.2.7 on 2026-09-15 14:34

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import hashlib
import hmac
import json


def backfill_environment_fingerprints(apps, schema_editor):
    environment_model = apps.get_model('perf_testing', 'PerfEnvironment')
    for environment in environment_model.objects.using(schema_editor.connection.alias).iterator():
        if not ((environment.scope == 'GLOBAL' and environment.project_id is None)
                or (environment.scope == 'PROJECT' and environment.project_id is not None)):
            raise RuntimeError('存在作用域与项目不匹配的历史压测环境，请修正后重新迁移')
        content = {key: getattr(environment, key) for key in
                   ('name', 'scope', 'project_id', 'base_url', 'headers', 'variables', 'verify_ssl')}
        encoded = json.dumps(content, sort_keys=True, ensure_ascii=False, separators=(',', ':')).encode()
        environment.content_hash = hmac.new(settings.SECRET_KEY.encode(), encoded, hashlib.sha256).hexdigest()
        environment.save(update_fields=['content_hash'], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('perf_testing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfenvironment',
            name='content_hash',
            field=models.CharField(blank=True, db_comment='环境内容 HMAC-SHA256 指纹', editable=False, max_length=64, verbose_name='内容指纹'),
        ),
        migrations.AddField(
            model_name='perfenvironment',
            name='version',
            field=models.PositiveIntegerField(db_comment='环境内容版本', default=1, editable=False, verbose_name='配置版本'),
        ),
        migrations.AddField(
            model_name='perfscenario',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='显式选择的项目环境', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='perf_testing.perfenvironment', verbose_name='项目环境'),
        ),
        migrations.AddField(
            model_name='perfscenario',
            name='global_environment',
            field=models.ForeignKey(blank=True, db_comment='显式选择的全局环境', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='global_scenarios', to='perf_testing.perfenvironment', verbose_name='全局环境'),
        ),
        migrations.RunPython(backfill_environment_fingerprints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='perfenvironment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('project__isnull', True), ('scope', 'GLOBAL')), models.Q(('project__isnull', False), ('scope', 'PROJECT')), _connector='OR'), name='perf_env_valid_scope_project'),
        ),
    ]
