# Generated by Django 4.2.7 on 2026-09-15 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perf_testing', '0003_persistent_environments'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfscenario',
            name='account_pool_group',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='perfdatafile',
            name='file_type',
            field=models.CharField(choices=[('CSV', 'CSV 参数化数据'), ('JMX', 'JMeter 脚本'), ('UPLOAD', '请求上传文件'), ('ACCOUNT', '私密账号池')], db_comment='文件类型：CSV参数化数据/JMX脚本', default='CSV', max_length=10, verbose_name='文件类型'),
        ),
        migrations.CreateModel(
            name='PerfAccountPoolVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('private_file', models.CharField(editable=False, max_length=64)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('columns', models.JSONField(default=list)),
                ('identity_column', models.CharField(max_length=128)),
                ('field_mapping', models.JSONField(default=dict)),
                ('group_column', models.CharField(blank=True, default='', max_length=128)),
                ('groups', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_versions', to='perf_testing.perfdatafile')),
            ],
            options={
                'db_table': 'perf_account_pool_versions',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='perfexecution',
            name='account_pool_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='perf_testing.perfaccountpoolversion'),
        ),
        migrations.AddField(
            model_name='perfscenario',
            name='account_pool_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='perf_testing.perfaccountpoolversion'),
        ),
        migrations.AddConstraint(
            model_name='perfaccountpoolversion',
            constraint=models.UniqueConstraint(fields=('pool', 'version'), name='perf_pool_version_unique'),
        ),
    ]
